## To modify by developer(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'raspberrypi'  # Updated to reflect the plugin's purpose

package-url = 'https://github.com/SosaSol/pymodaq_plugins_raspberrypi'  # Updated with the correct repository URL
description = 'A PyMoDAQ plugin for controlling Raspberry Pi GPIO and servo motors using gpiozero and pigpio.'

author = 'Solim Rovera'
author-email = 'solim.rovera@student.isae-supaero.fr'
license = 'MIT'

[plugin-install]
# Packages required for your plugin:
packages-required = ['pymodaq>=4.3.6', 'gpiozero', 'pigpio']

[features]  # Defines the plugin features contained in this plugin
instruments = true  # This plugin contains instrument classes
extensions = false  # This plugin does not contain dashboard extensions
models = false  # No PID models or optimization models included
h5exporters = false  # No custom h5 file exporters included
scanners = false  # No custom scan layouts included
